@startuml ユースケース図
left to right direction

actor メンバー
actor 管理者
actor 運営

package web {
  メンバー --> (Slackで褒めたものが自動で集計される)
  メンバー --> (褒めた数の推移をグラフで見る)
  メンバー --> (Slackの活用指数やアドバイスを確認できる)
  メンバー --> (褒めた数で惑星を開発できる) 
  メンバー --> (褒め言葉のタイムラインを見る)
  メンバー --> (ワークスペースのコミュニケーションネットワークを見る)
  管理者 --> (支払いを確認する)
}

package 管理画面 {
 運営 --> (請求先を確認する)
}

note right of web
  褒めた数で惑星を、の粒度に違和感  
  数を積み重ねることでゲーミフィケーション的な活性化をする
endnote 

@enduml
